{
    'name': 'Smart Operations Center',
    'version': '18.0.1.0.0',
    'category': 'Operations/Operations',
    'summary': 'Business process health, operational risk, impact analysis and action management',
    'description': 'Detect operational risks, understand their business impact, and manage corrective actions from one Odoo workspace.',
    'author': 'Farid SLIMANI',
    'license': 'OPL-1',
    "website": "https://slimanifarid.github.io",
    "license": "LGPL-3",
    'price': 68.00,
    'currency': 'EUR',
    'depends': ['base', 'mail'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/issue_sequences.xml',
        'data/default_processes.xml',
        'data/cron.xml',
        'views/operations_issue_views.xml',
        'views/operations_rule_views.xml',
        'views/operations_process_views.xml',
        'views/operations_baseline_views.xml',
        'views/operations_action_views.xml',
        'views/operations_escalation_views.xml',
        'views/operations_menus.xml',
        'wizard/investigate_issue_views.xml',
        'wizard/resolve_issue_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'smart_operations_center/static/src/dashboard/operations_dashboard.js',
            'smart_operations_center/static/src/dashboard/operations_dashboard.xml',
            'smart_operations_center/static/src/styles/operations_dashboard.scss',
        ],
    },
    'post_init_hook': 'post_init_hook',
    'application': True,
    'installable': True,
}
