from datetime import timedelta

from odoo import _, api, fields, models
from odoo.exceptions import AccessError


class PickingException(models.Model):
    _name = 'fs.picking.exception'
    _description = 'Picking Exception'
    _order = 'severity desc, age_days desc, id desc'
    _check_company_auto = True
    _inherit = ['mail.thread', 'mail.activity.mixin']

    picking_id = fields.Many2one('stock.picking', required=True, index=True, ondelete='cascade')
    company_id = fields.Many2one(related='picking_id.company_id', store=True, index=True)
    partner_id = fields.Many2one(related='picking_id.partner_id', store=True)
    picking_type_id = fields.Many2one(related='picking_id.picking_type_id', store=True)
    warehouse_id = fields.Many2one(related='picking_id.picking_type_id.warehouse_id', store=True)
    exception_type = fields.Selection([
        ('shortage', 'Shortage'),
        ('reservation', 'Reservation'),
        ('overdue', 'Overdue'),
        ('blocked', 'Blocked'),
        ('dependency', 'Dependency'),
        ('backorder', 'Backorder'),
    ], required=True, index=True)
    severity = fields.Selection([
        ('warning', 'Warning'),
        ('critical', 'Critical'),
    ], required=True, index=True, tracking=True)
    state = fields.Selection([
        ('open', 'Open'),
        ('resolved', 'Resolved'),
    ], default='open', tracking=True, index=True)
    details = fields.Text(required=True)
    first_seen = fields.Datetime(default=fields.Datetime.now, readonly=True, index=True)
    last_seen = fields.Datetime(default=fields.Datetime.now, readonly=True)
    resolved_at = fields.Datetime(readonly=True)
    assigned_user_id = fields.Many2one('res.users', string='Responsible', check_company=True)
    age_days = fields.Integer(compute='_compute_age', store=True, index=True)

    _type_unique = models.Constraint(
        'unique (picking_id,exception_type)',
        'Only one analysis row per exception type is allowed per picking.',
    )

    @api.depends('first_seen', 'last_seen', 'resolved_at', 'state')
    def _compute_age(self):
        now = fields.Datetime.now()
        for rec in self:
            if not rec.first_seen:
                rec.age_days = 0
                continue
            end = rec.resolved_at if rec.state == 'resolved' and rec.resolved_at else now
            rec.age_days = max((end - rec.first_seen).days, 0)

    @api.model_create_multi
    def create(self, vals_list):
        if not self.env.context.get('fs_picking_exception_internal'):
            raise AccessError(_('Picking exceptions are generated by the analysis engine and cannot be created manually.'))
        return super().create(vals_list)

    def write(self, vals):
        protected = {
            'picking_id', 'company_id', 'exception_type', 'severity', 'details',
            'first_seen', 'last_seen', 'resolved_at', 'age_days', 'state', 'assigned_user_id',
        }
        if protected.intersection(vals) and not self.env.context.get('fs_picking_exception_internal'):
            raise AccessError(_('Picking exception fields can only be changed through the workflow or analysis engine.'))
        return super().write(vals)

    def unlink(self):
        if not self.env.context.get('fs_picking_exception_internal'):
            raise AccessError(_('Picking exception rows are managed by the analysis engine.'))
        return super().unlink()


    def action_open_picking(self):
        self.ensure_one()
        return {
            'type': 'ir.actions.act_window',
            'res_model': 'stock.picking',
            'view_mode': 'form',
            'res_id': self.picking_id.id,
            'name': _('Transfer'),
        }

    def action_assign_to_me(self):
        if not self.env.user.has_group('stock.group_stock_user'):
            raise AccessError(_('Only inventory users can assign picking exceptions.'))
        self.with_context(fs_picking_exception_internal=True).write({'assigned_user_id': self.env.user.id})
        return True

    def action_resolve(self):
        if not self.env.user.has_group('stock.group_stock_user'):
            raise AccessError(_('Only inventory users can resolve picking exceptions.'))
        self.with_context(fs_picking_exception_internal=True).write({
            'state': 'resolved',
            'resolved_at': fields.Datetime.now(),
            'last_seen': fields.Datetime.now(),
        })
        return True

    def action_reopen(self):
        if not self.env.user.has_group('stock.group_stock_user'):
            raise AccessError(_('Only inventory users can reopen picking exceptions.'))
        now = fields.Datetime.now()
        self.with_context(fs_picking_exception_internal=True).write({
            'state': 'open',
            'first_seen': now,
            'last_seen': now,
            'resolved_at': False,
        })
        return True

    @api.model
    def _build_exceptions(self, picking, config):
        """Return the currently detectable operational exceptions for one picking."""
        items = []
        open_moves = picking.move_ids.filtered(lambda move: move.state not in ('done', 'cancel'))
        if not open_moves:
            return items

        if any(
            move.product_id
            and move.product_id.is_storable
            and move.product_id.uom_id.compare(
                move.forecast_availability or 0.0,
                move.product_uom._compute_quantity(
                    move.product_uom_qty,
                    move.product_id.uom_id,
                    rounding_method='HALF-UP',
                ),
            ) < 0
            for move in open_moves
        ):
            items.append((
                'shortage',
                'critical',
                _('One or more open moves have insufficient forecast availability.'),
            ))

        if any(move.state == 'partially_available' for move in open_moves):
            items.append((
                'reservation',
                'warning',
                _('One or more moves are only partially reserved.'),
            ))

        now = fields.Datetime.now()
        if picking.has_deadline_issue or (
            picking.scheduled_date
            and now > picking.scheduled_date + timedelta(minutes=config.overdue_minutes)
        ):
            items.append((
                'overdue',
                'critical',
                _('The transfer is late against its scheduled date or deadline.'),
            ))

        if picking.state == 'waiting':
            items.append((
                'blocked',
                'warning',
                _('The transfer is waiting for another operation or availability.'),
            ))
            if any(
                move.move_orig_ids.filtered(lambda origin: origin.state not in ('done', 'cancel'))
                for move in open_moves
            ):
                items.append((
                    'dependency',
                    'warning',
                    _('Upstream stock moves are still open.'),
                ))

        if picking.backorder_id:
            items.append((
                'backorder',
                'warning',
                _('This transfer is part of a backorder chain.'),
            ))
        return items

    @api.model
    def refresh(self, pickings=None):
        """Refresh exception records without creating duplicate rows or stale ages."""
        Picking = self.env['stock.picking']
        if pickings is None or not pickings:
            pickings = Picking.search([('state', 'not in', ('done', 'cancel'))], order='id')
        else:
            pickings = pickings.filtered(lambda picking: picking.state not in ('done', 'cancel'))

        if not pickings:
            return True

        configs = self.env['fs.picking.exception.config'].sudo().search([
            ('company_id', 'in', pickings.company_id.ids)
        ])
        config_by_company = {config.company_id.id: config for config in configs}
        existing = self.search([('picking_id', 'in', pickings.ids)])
        existing_by_picking = {}
        for rec in existing:
            existing_by_picking.setdefault(rec.picking_id.id, {})[rec.exception_type] = rec

        for picking in pickings:
            config = config_by_company.get(picking.company_id.id)
            if not config:
                config = self.env['fs.picking.exception.config'].new({
                    'company_id': picking.company_id.id,
                    'overdue_minutes': 0,
                    'critical_after_days': 2,
                    'notification_mode': 'none',
                })

            detected = {
                item[0]: item[1:]
                for item in self._build_exceptions(picking, config)
            }
            existing_for_picking = existing_by_picking.get(picking.id, {})
            now = fields.Datetime.now()

            for exception_type, (severity, details) in detected.items():
                rec = existing_for_picking.get(exception_type)
                if rec:
                    values = {
                        'severity': severity,
                        'details': details,
                        'last_seen': now,
                    }
                    reopened = rec.state == 'resolved'
                    if reopened:
                        values.update({
                            'state': 'open',
                            'first_seen': now,
                            'resolved_at': False,
                        })
                    if (
                        values['severity'] == 'warning'
                        and config.critical_after_days
                        and max((now - (values.get('first_seen') or rec.first_seen)).days, 0)
                        >= config.critical_after_days
                    ):
                        values['severity'] = 'critical'
                    if not rec.assigned_user_id:
                        values['assigned_user_id'] = picking.user_id.id if picking.user_id else False
                    rec.with_context(fs_picking_exception_internal=True).write(values)
                    if reopened and config.notification_mode == 'activity':
                        user = config.notification_user_id or picking.user_id
                        if user:
                            rec.activity_schedule(
                                'mail.mail_activity_data_todo',
                                user_id=user.id,
                                summary=_('Picking exception reopened'),
                                note=details,
                            )
                else:
                    rec = self.with_context(fs_picking_exception_internal=True).create({
                        'picking_id': picking.id,
                        'exception_type': exception_type,
                        'severity': severity,
                        'details': details,
                        'assigned_user_id': picking.user_id.id if picking.user_id else False,
                    })
                    if severity == 'critical' and config.notification_mode == 'activity':
                        user = config.notification_user_id or picking.user_id
                        if user:
                            rec.activity_schedule(
                                'mail.mail_activity_data_todo',
                                user_id=user.id,
                                summary=_('Critical picking exception'),
                                note=details,
                            )

            for exception_type, rec in existing_for_picking.items():
                if exception_type in detected or rec.state != 'open':
                    continue
                rec.with_context(fs_picking_exception_internal=True).write({
                    'state': 'resolved',
                    'resolved_at': now,
                    'last_seen': now,
                })
        return True

    @api.model
    def _resolve_closed_pickings(self, batch_size=500):
        """Close open exception rows whose source transfer is now done or cancelled."""
        last_id = 0
        while True:
            records = self.search(
                [
                    ('id', '>', last_id),
                    ('state', '=', 'open'),
                    ('picking_id.state', 'in', ('done', 'cancel')),
                ],
                order='id',
                limit=batch_size,
            )
            if not records:
                break
            records.with_context(fs_picking_exception_internal=True).write({
                'state': 'resolved',
                'resolved_at': fields.Datetime.now(),
                'last_seen': fields.Datetime.now(),
            })
            last_id = records[-1].id

    @api.model
    def cron_refresh(self, batch_size=500):
        last_id = 0
        while True:
            pickings = self.env['stock.picking'].search(
                [('id', '>', last_id), ('state', 'not in', ('done', 'cancel'))],
                order='id',
                limit=batch_size,
            )
            if not pickings:
                break
            self.refresh(pickings)
            last_id = pickings[-1].id
        self._resolve_closed_pickings(batch_size=batch_size)
        return True
