{
    'name': 'PO Vendor Acknowledgment',
    'version': '18.0.1.1.0',
    'category': 'Purchase',
    'summary': 'Capture supplier acceptance of quantities and dates without allowing direct purchase order edits.',
    'author': 'Farid SLIMANI',
    'website': 'https://apps.odoo.com/apps/modules/browse?author=Farid%20SLIMANI',
    'license': 'OPL-1',
    'price': 39.0,
    'currency': 'EUR',
    'depends': ['purchase', 'portal', 'mail'],
    'data': ['security/security.xml', 'security/ir.model.access.csv', 'views/views.xml', 'views/portal_templates.xml', 'data/mail_template.xml'],
    'demo': [],
    'installable': True,
    'application': False,
    'auto_install': False,
    'images': ['static/description/banner.png', 'static/description/icon.png'],
}
