from . import eduflow_academic_period
from . import eduflow_academic_year
from . import eduflow_account_move
from . import eduflow_admission
from . import eduflow_admission_document_line
from . import eduflow_attendance
from . import eduflow_attendance_wizard
from . import eduflow_classroom
from . import eduflow_dashboard
from . import eduflow_document_type
from . import eduflow_enrollment
from . import eduflow_exam
from . import eduflow_fee
from . import eduflow_fee_reminder_log
from . import eduflow_fee_type
from . import eduflow_grade
from . import eduflow_level
from . import eduflow_level_subject_hours
from . import eduflow_parent
from . import eduflow_payment
from . import eduflow_program
from . import eduflow_report_card
from . import eduflow_res_config_settings
from . import eduflow_res_users
from . import eduflow_room
from . import eduflow_student
from . import eduflow_student_parent_rel
from . import eduflow_subject
from . import eduflow_teacher_availability
from . import eduflow_teacher
from . import eduflow_time_slot
from . import eduflow_timetable
from . import eduflow_timetable_generate_wizard
from . import dashboard_service
