from odoo import api, fields, models, _


class SmartOperationsAction(models.Model):
    _name = 'smart.operations.action'
    _description = 'Operational Action'
    _order = 'state, due_date, id'

    name = fields.Char(required=True)
    issue_id = fields.Many2one('smart.operations.issue', required=True, ondelete='cascade', index=True)
    action_type = fields.Selection([
        ('activity', 'Create Activity'),
        ('assign', 'Assign'),
        ('email', 'Send Email'),
        ('escalate', 'Escalate'),
        ('resolve', 'Resolve'),
        ('snooze', 'Snooze'),
    ], required=True)
    state = fields.Selection([
        ('pending', 'Pending'), ('done', 'Done'), ('cancelled', 'Cancelled')
    ], default='pending', required=True, index=True)
    responsible_id = fields.Many2one('res.users', ondelete='set null')
    due_date = fields.Datetime()
    completed_at = fields.Datetime(readonly=True)
    activity_id = fields.Many2one('mail.activity', readonly=True, ondelete='set null')
    notes = fields.Text()
    escalation_policy_id = fields.Many2one('smart.operations.escalation', ondelete='set null')
    escalation_level = fields.Integer(default=1)

    @api.model_create_multi
    def create(self, vals_list):
        records = super().create(vals_list)
        for action in records:
            action._ensure_activity()
        return records

    def _ensure_activity(self):
        Activity = self.env['mail.activity']
        todo_type = self.env.ref('mail.mail_activity_data_todo', raise_if_not_found=False)
        for action in self.filtered(lambda r: r.action_type == 'activity' and r.issue_id and r.responsible_id and not r.activity_id):
            if not todo_type:
                continue
            existing = Activity.search([
                ('res_model', '=', action.issue_id._name),
                ('res_id', '=', action.issue_id.id),
                ('activity_type_id', '=', todo_type.id),
                ('user_id', '=', action.responsible_id.id),
                ('summary', '=', action.name),
            ], limit=1)
            activity = existing or action.issue_id.activity_schedule(
                'mail.mail_activity_data_todo',
                user_id=action.responsible_id.id,
                date_deadline=(action.due_date.date() if action.due_date else fields.Date.context_today(action)),
                summary=action.name,
                note=action.notes or _('Operational action generated by Smart Operations Center.'),
            )
            if activity:
                action.activity_id = activity.id if hasattr(activity, 'id') else activity

    def action_complete(self):
        for action in self.filtered(lambda r: r.state == 'pending'):
            action._ensure_activity()
            action.write({'state': 'done', 'completed_at': fields.Datetime.now()})
        return True
