{
    'name': 'Manufacturing Readiness Check',
    'version': '19.0.1.1.0',
    'category': 'Manufacturing',
    'summary': 'Check whether a manufacturing order is genuinely ready before production starts.',
    'author': 'Farid SLIMANI',
    'website': 'https://apps.odoo.com/apps/modules/browse?author=Farid%20SLIMANI',
    'license': 'OPL-1',
    'price': 39.0,
    'currency': 'EUR',
    'depends': ['mrp', 'stock', 'mail'],
    'data': ['security/security.xml', 'security/ir.model.access.csv', 'views/views.xml'],
    'demo': [],
    'installable': True,
    'application': False,
    'auto_install': False,
    'images': ['static/description/banner.png', 'static/description/icon.png'],
}
