{
    'name': 'Warehouse Cut-off Manager',
    'version': '18.0.1.1.0',
    'category': 'Inventory',
    'summary': 'Define warehouse shipping cut-off times and warn when transfers are at risk of missing them.',
    'author': 'Farid SLIMANI',
    'website': 'https://apps.odoo.com/apps/modules/browse?author=Farid%20SLIMANI',
    'license': 'OPL-1',
    'price': 29.0,
    'currency': 'EUR',
    'depends': ['stock', 'delivery', 'sale_management', 'mail'],
    'data': ['security/security.xml', 'security/ir.model.access.csv', 'views/views.xml', 'data/cron.xml'],
    'demo': [],
    'installable': True,
    'application': False,
    'auto_install': False,
    'images': ['static/description/banner.png', 'static/description/icon.png'],
}
