import re
from datetime import timedelta

from odoo import _, api, fields, models
from odoo.exceptions import AccessError, UserError


class SaleOrderDuplicateMatch(models.Model):
    _name = 'fs.sale.order.duplicate.match'
    _description = 'Sales Order Duplicate Match'
    _order = 'score desc, id desc'
    _check_company_auto = True
    _inherit = ['mail.thread']

    sale_order_id = fields.Many2one('sale.order', required=True, index=True, ondelete='cascade')
    candidate_order_id = fields.Many2one('sale.order', required=True, index=True, ondelete='cascade')
    company_id = fields.Many2one(related='sale_order_id.company_id', store=True, index=True)
    score = fields.Integer(required=True, index=True)
    level = fields.Selection([('possible', 'Possible'), ('likely', 'Likely')], required=True)
    factors = fields.Text(required=True)
    state = fields.Selection(
        [('open', 'Open'), ('ignored', 'Ignored'), ('marked_duplicate', 'Marked Duplicate')],
        default='open',
        required=True,
        index=True,
        tracking=True,
    )
    decision_note = fields.Text()
    decided_by = fields.Many2one('res.users', readonly=True)
    decision_date = fields.Datetime(readonly=True)

    _pair_unique = models.Constraint(
        'unique (sale_order_id,candidate_order_id)',
        'Each order pair can only have one duplicate match.',
    )

    @api.model_create_multi
    def create(self, vals_list):
        if not self.env.context.get('fs_duplicate_internal'):
            raise AccessError(_('Duplicate analysis rows are generated by the detection engine.'))
        return super().create(vals_list)

    def write(self, vals):
        protected = {
            'sale_order_id', 'candidate_order_id', 'company_id', 'score', 'level',
            'factors', 'state', 'decided_by', 'decision_date',
        }
        if protected.intersection(vals) and not self.env.context.get('fs_duplicate_internal'):
            raise AccessError(_('Duplicate analysis fields can only be changed through the review workflow.'))
        return super().write(vals)

    def unlink(self):
        if not self.env.context.get('fs_duplicate_internal'):
            raise AccessError(_('Duplicate review history cannot be deleted manually.'))
        return super().unlink()


    def action_ignore(self, note=False):
        for rec in self:
            rec.with_context(fs_duplicate_internal=True).write({
                'state': 'ignored',
                'decided_by': self.env.user.id,
                'decision_date': fields.Datetime.now(),
                'decision_note': note or rec.decision_note,
            })
        return True

    def action_mark_duplicate(self, note=False):
        if not self.env.user.has_group('sales_team.group_sale_manager'):
            raise AccessError(_('Only sales managers can mark an order pair as a duplicate.'))
        for rec in self:
            rec.with_context(fs_duplicate_internal=True).write({
                'state': 'marked_duplicate',
                'decided_by': self.env.user.id,
                'decision_date': fields.Datetime.now(),
                'decision_note': note or rec.decision_note,
            })
            rec.sale_order_id.message_post(
                body=_(
                    'Order %(order)s was marked as a duplicate of %(candidate)s by %(user)s.',
                    order=rec.sale_order_id.name,
                    candidate=rec.candidate_order_id.name,
                    user=self.env.user.display_name,
                )
            )
        return True


class SaleOrderDuplicateGuardMixin(models.AbstractModel):
    _name = 'fs.sale.order.duplicate.mixin'
    _description = 'Sales Order Duplicate Detection Service'

    @staticmethod
    def _normalize(value):
        return re.sub(r'[^A-Z0-9]+', '', (value or '').upper())

    def _score_orders(self, order, candidate, config):
        score = 25
        factors = ['Same customer']
        ref1 = self._normalize(order.client_order_ref)
        ref2 = self._normalize(candidate.client_order_ref)
        if config.compare_reference and ref1 and ref2 and ref1 == ref2:
            score += 30
            factors.append('Same customer reference')

        if config.compare_lines:
            products1 = {line.product_id.id: line.product_uom_qty for line in order.order_line if line.product_id}
            products2 = {line.product_id.id: line.product_uom_qty for line in candidate.order_line if line.product_id}
            if products1 and products1 == products2:
                score += 25
                factors.append('Same products and quantities')
            elif products1 and products2:
                overlap = len(set(products1) & set(products2)) / max(len(set(products1) | set(products2)), 1)
                quantity_matches = True
                for product_id in set(products1) & set(products2):
                    if abs(products1[product_id] - products2[product_id]) > config.quantity_tolerance:
                        quantity_matches = False
                        break
                if overlap >= 0.75 and quantity_matches:
                    score += 18
                    factors.append('High product overlap')
                elif overlap >= 0.5:
                    score += 10
                    factors.append('Moderate product overlap')

        if order.currency_id == candidate.currency_id:
            if abs(order.amount_total - candidate.amount_total) <= config.amount_tolerance:
                score += 10
                factors.append('Amounts within configured tolerance')
        if order.date_order and candidate.date_order:
            if abs((order.date_order - candidate.date_order).total_seconds()) <= 2 * 86400:
                score += 10
                factors.append('Orders placed within two days')
        return min(score, 100), factors
