from odoo import _, api, fields, models
from odoo.exceptions import UserError


class MrpReadinessCheck(models.Model):
    _name = 'fs.mrp.readiness.check'
    _description = 'Manufacturing Readiness Check'
    _inherit = ['mail.thread']
    _check_company_auto = True
    _order = 'checked_at desc, id desc'

    production_id = fields.Many2one('mrp.production', required=True, index=True, ondelete='cascade')
    company_id = fields.Many2one(related='production_id.company_id', store=True, index=True)
    checked_at = fields.Datetime(readonly=True)
    status = fields.Selection(
        [('ready', 'Ready'), ('warning', 'Warning'), ('blocked', 'Blocked')],
        default='blocked',
        required=True,
        index=True,
        tracking=True,
    )
    blocker_count = fields.Integer(compute='_compute_counts', store=True)
    warning_count = fields.Integer(compute='_compute_counts', store=True)
    item_ids = fields.One2many('fs.mrp.readiness.item', 'check_id', copy=False)
    summary = fields.Text(readonly=True)

    _production_unique = models.Constraint(
        'unique (production_id)',
        'Only one current readiness record is allowed per manufacturing order.',
    )

    @api.model_create_multi
    def create(self, vals_list):
        if not self.env.context.get('fs_mrp_readiness_internal'):
            raise UserError(_('Readiness checks are generated by the readiness workflow.'))
        return super().create(vals_list)

    def write(self, vals):
        protected = {'production_id', 'company_id', 'checked_at', 'status', 'blocker_count', 'warning_count', 'summary', 'item_ids'}
        if protected.intersection(vals) and not self.env.context.get('fs_mrp_readiness_internal'):
            raise UserError(_('Readiness results are generated by the check engine and cannot be edited manually.'))
        return super().write(vals)

    @api.depends('item_ids.severity')
    def _compute_counts(self):
        for rec in self:
            rec.blocker_count = len(rec.item_ids.filtered(lambda x: x.severity == 'blocker'))
            rec.warning_count = len(rec.item_ids.filtered(lambda x: x.severity == 'warning'))

    def unlink(self):
        if not self.env.context.get('fs_mrp_readiness_internal'):
            raise UserError(_('Readiness checks are generated audit records and cannot be deleted manually.'))
        return super().unlink()

    def action_check(self):
        self.ensure_one()
        return self._run_check()

    def _run_check(self):
        self.ensure_one()
        production = self.production_id
        self.item_ids.with_context(fs_mrp_readiness_internal=True).unlink()
        items = []
        for move in production.move_raw_ids.filtered(
            lambda m: m.state not in ('cancel', 'done')
            and m.product_id
            and not m.product_uom.is_zero(m.product_uom_qty)
            and not m.picked
        ):
            available = move.forecast_availability or 0.0
            if move.product_uom.compare(available, move.product_uom_qty) < 0:
                items.append((0, 0, {
                    'name': _('Component availability: %s', move.product_id.display_name),
                    'severity': 'blocker',
                    'category': 'component',
                    'detail': _(
                        'Required %(required).2f %(uom)s, forecast availability %(available).2f.',
                        required=move.product_uom_qty,
                        uom=move.product_uom.name,
                        available=available,
                    ),
                }))
        config = self.env['fs.mrp.readiness.config'].sudo().search(
            [('company_id', '=', production.company_id.id)], limit=1
        )
        if (config.check_workcenters if config else True) and production.workorder_ids:
            for workorder in production.workorder_ids:
                if not workorder.workcenter_id:
                    items.append((0, 0, {
                        'name': _('Work center missing'),
                        'severity': 'blocker',
                        'category': 'workcenter',
                        'detail': _('Operation %(operation)s has no work center.', operation=workorder.operation_id.display_name),
                    }))
                elif not workorder.workcenter_id.resource_calendar_id:
                    items.append((0, 0, {
                        'name': _('Work center calendar missing'),
                        'severity': 'warning',
                        'category': 'workcenter',
                        'detail': _('Work center %(workcenter)s has no resource calendar.', workcenter=workorder.workcenter_id.display_name),
                    }))
                elif workorder.state in ('pending', 'waiting', 'blocked'):
                    items.append((0, 0, {
                        'name': _('Operation is not ready'),
                        'severity': 'warning',
                        'category': 'operation',
                        'detail': _('Operation %(operation)s is currently in state %(state)s.', operation=workorder.operation_id.display_name, state=workorder.state),
                    }))

        forecast_risk = production.move_raw_ids.filtered(
            lambda move: move.forecast_expected_date and production.date_start
            and move.forecast_expected_date > production.date_start
            and move.state not in ('done', 'cancel')
        )
        for move in forecast_risk:
            items.append((0, 0, {
                'name': _('Component arrival risk'),
                'severity': 'warning',
                'category': 'component',
                'detail': _('Component %(product)s is forecast to arrive after the production start date.', product=move.product_id.display_name),
            }))
        if production.bom_id and production.move_raw_ids and production.reservation_state != 'assigned' and not any(item[2]['severity'] == 'blocker' for item in items):
            items.append((0, 0, {
                'name': _('Components are not fully reserved'),
                'severity': 'blocker',
                'category': 'component',
                'detail': _('Odoo reports this manufacturing order is waiting for component availability.'),
            }))
        blockers = sum(1 for item in items if item[2]['severity'] == 'blocker')
        warnings = sum(1 for item in items if item[2]['severity'] == 'warning')
        policy = config.blocking_policy if config else 'block'
        effective_status = 'blocked' if blockers and policy == 'block' else 'warning' if blockers or warnings else 'ready'
        self.with_context(fs_mrp_readiness_internal=True).write({
            'checked_at': fields.Datetime.now(),
            'status': effective_status,
            'summary': _(
                'Blockers: %(blockers)s | Warnings: %(warnings)s | Policy: %(policy)s',
                blockers=blockers,
                warnings=warnings,
                policy='Block' if policy == 'block' else 'Warn Only',
            ),
            'item_ids': items,
        })
        return True

    def action_open_mo(self):
        self.ensure_one()
        return {
            'type': 'ir.actions.act_window',
            'res_model': 'mrp.production',
            'view_mode': 'form',
            'res_id': self.production_id.id,
            'name': _('Manufacturing Order'),
        }


class MrpReadinessItem(models.Model):
    _name = 'fs.mrp.readiness.item'
    _description = 'MRP Readiness Check Item'
    _check_company_auto = True

    @api.model_create_multi
    def create(self, vals_list):
        if not self.env.context.get('fs_mrp_readiness_internal'):
            raise UserError(_('Readiness items are generated by the readiness engine.'))
        return super().create(vals_list)

    check_id = fields.Many2one('fs.mrp.readiness.check', required=True, ondelete='cascade')
    company_id = fields.Many2one(related='check_id.company_id', store=True, index=True)
    name = fields.Char(required=True)
    category = fields.Selection([
        ('component', 'Component'),
        ('workcenter', 'Work Center'),
        ('operation', 'Operation'),
        ('other', 'Other'),
    ], required=True)
    severity = fields.Selection([
        ('blocker', 'Blocker'),
        ('warning', 'Warning'),
        ('info', 'Info'),
    ], required=True)
    detail = fields.Text(required=True)

    def write(self, vals):
        if vals and not self.env.context.get('fs_mrp_readiness_internal'):
            raise UserError(_('Readiness items are generated by the readiness engine and cannot be edited manually.'))
        return super().write(vals)

    def unlink(self):
        if not self.env.context.get('fs_mrp_readiness_internal'):
            raise UserError(_('Readiness items are generated by the readiness engine.'))
        return super().unlink()


